environments:
  dev:
    base_url: "https://the-internet.herokuapp.com"
    api_base_url: "https://jsonplaceholder.typicode.com"
  stage:
    base_url: "https://staging.example.com"
    api_base_url: "https://api.staging.example.com"
  prod:
    base_url: "https://example.com"
    api_base_url: "https://api.example.com"

default_env: "dev"